[package]
name = "program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
solana-program = { workspace = true } 
bincode = { workspace = true }
lib = { workspace = true }
